export * from "./Logo";
export * from "./Person";
export * from "./HeroSection";
export * from "./SecondSection";
export * from "./DynamicBackground";
export * from "./TravelingBlob";
export * from "./ThirdSection";
export * from "./NavWrapper";
export * from "./AnimatedText";
